create table users (
    id int primary key generated by default as identity,
    email varchar(100) unique,
    password varchar(512),
    first_name varchar(100),
    second_name varchar(100),
    third_name varchar(100),
    phone int unique,
    birthdate date,
    passport_series int,
    passport_number int,
    created_at timestamp without time zone
);

create table roles (
    id int primary key generated by default as identity,
    name varchar(15) unique
);
insert into roles (name) values ('ROLE_ADMIN'),
                                ('ROLE_MANAGER'),
                                ('ROLE_CONSIGNER'),
                                ('ROLE_CARRIER');

create table user_role (
    user_id int references users(id),
    role_id int references roles(id),
    primary key (user_id, role_id)
);
